### ISSUE TITLE
{this.props.header} in page 47 is confusing

### ISSUE THREAD

**Issue by asamamun** [PacktPublishing/React-16-Essentials-Second-Edition#1]
in chapter 4 page 47:
```
class ReactClass extends Component {
render() {
const componentState = {
isHidden: false
};
if (componentState.isHidden) {
return null;
}
return (
<h1 className="header">{this.props.header}</h1>
);
}
}
```
My question is: what is {this.props.header} here? this is so confising...

**Comment by asamamun** [comment]
After some searching i figured out:
```
class Welcome extends React.Component {
  render() {
    return <h1>Hello {this.props.name}</h1>;
  }
}
const element = <Welcome name="Sara" />;
```
the property is passed to the component, similar to how an argument is passed to a function.
But this book wrote tones of lines with no actual output and will make react even more confusing. Disgusting...

**Comment by githubce** [comment]
This book was published in 2017. Since then, there have been updates in the codes.
